### ISSUE TITLE
Feature Request [Dark Mode]

### ISSUE THREAD

**Issue by prestmango** [divamgupta/diffusionbee-stable-diffusion-ui#86] opened 2022-09-21 23:25 UTC
First off, you are doing the work of God ! Phenomenal system to run stable diffusion on Mac.
If possible, a dark mode app would be amazing, to seamlessly use this, and match the modern dark U.I of a Mac. If there was a setting in preferences to switch the U.I to be dark grey, or black, that would be amazing :)))

**Comment by LePips** [comment] 2022-09-22 03:36
Duplicate of https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/issues/41

**Closed** 2022-09-22 03:38 UTC
