### ISSUE TITLE
Updating to new version cleared my history

### ISSUE THREAD

**Issue by batchku** [divamgupta/diffusionbee-stable-diffusion-ui#144] opened 2022-09-28 14:48 UTC
When I updated from the 0.2 version to the latest, I lost all my history; this is very unfortunate.  It would be great if this does not happen in future updates.

**Comment by 0x62** [comment] 2022-09-28 15:08
v0.3 adds persistent history so this shouldn't happen in future now you've updated to latest version

**Comment by Leland** [comment] 2022-10-02 22:30
Dupe of #108

**Closed** 2022-10-04 00:01 UTC
